export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  CSRF_BLOCKED: "CSRF_BLOCKED",
  RATE_LIMITED: "RATE_LIMITED",
  RATE_LIMIT_UNAVAILABLE: "RATE_LIMIT_UNAVAILABLE",
  REQUEST_TOO_LARGE: "REQUEST_TOO_LARGE",
} as const);

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
